### ISSUE TITLE
Don't send cursor movements for ignored files

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#108]
Open question: Should the editor plugin or the daemon prevent that?

**Comment by blinry** [comment]
This mostly seems a privacy issue, it tells peers that the file exists.

**Comment by blinry** [comment]
The plugin should probably stop sending cursor movements after it's "open" failed, right?

**Comment by zormit** [comment]
It seems both plugins are already correctly handling this case when open fails (which is would, when a file is ignored)
