### ISSUE TITLE
When using pre-commit, the `cargo check` step is often super slow

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#114]
It seems that it requires an entire re-compilation? Can we avoid that?

**Comment by blinry** [comment]
Also, we're surprised why we have to re-compile dependencies so often. Shouldn't it be enough if they're recompiled once, in debug and release mode?

**Comment by zormit** [comment]
Turns out we were _both_ on a dirty repository with some uncommitted `.cargo` configuration that slowed us down. So this was a homemade issue that doesn't exist on the published repository.
