### ISSUE TITLE
Document how we decided with the current way of securing our connection

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#117]
Write an ADR retrospectively how we came about to use libp2p and the preshared key encrypted transport.

**Comment by blinry** [comment]
Random collection of things this could go into:

"Security concept":

- Daemon should only ever write in its base directory
	- -> sandbox module
    - Exception: Socket file: /tmp/ethersync
- Attackk surface: Connections from the Internet
- People who don't have the shared secret should not:
	- Be able to read or write any content from our computer
- People who have the shared secret can:
	- Read/change/delete all content in the shared directory (by design)
		- (thought: Ideally, they wouldn't be able to delete `.ethersync/doc`...)

Properties of our chosen solution:

- Access is irrevokable, peers get the entire document history
- To kick someone out, others have to change the password
- libp2p gives us authentication of peers through the Peer ID
	- like with Signal, you have to verify the ID via an already trusted channel
	- It's part of the multiaddr, so you can be sure there's no MITM when given the multiaddr over a trusted channel

Alternatives to libp2p with private network:

- PSK-TLS
- TLS/QUIC library + PAKE (like CPace)

Advantages of libp2p:

- NAT circumvention features (hopefully)
- Few lines of code to have true p2p functionality (everyone is listening and can be dialed)

My writeup that we could copy from: https://discuss.libp2p.io/t/how-to-build-magic-wormhole-style-authorization/2419/2

**Comment by zormit** [comment]
Length/duration of a "session" / lifetime of a passphrase: in the note-taking use-case over a couple of weeks/months. => so far we are not considering a key-change (or whatever it's called). I think this is probably one of our biggest weaknesses, if we still want to have just 3-4 simple words.
