### ISSUE TITLE
The installation instructions don't work. 

### ISSUE THREAD

**Issue by MangoIV** [ethersync/ethersync#132]
Hi. I tried using `ethersync` but it seems like at least the installation instructions aren't up to date anymore, here's what I did: 
- install `ethersync` on remote, run it with `ethersync daemon playground --port 4242` 
- install `ethersync` on peer, run it with `ethersync dameon playground --peer <ip-address>:4242` and  I get 
```
thread 'tokio-runtime-worker' panicked at src/peer.rs:142:18:
Failed to parse argument as `Multiaddr`: InvalidMultiaddr
```

The same thing happens if one tries to use `<hostName>:<port>`

Additionally I'm quite confused about the `nvim` plugin. I wanted to try this out with somebody else and they reported it didn't work for them and it didn't work for me either. Isn't there something like the usual 
```lua 
require('ethersync').setup()
``` 
? 

I think it would be quite nice if ethersync wouldn't deviate from the usual conventions there, that would make using it simpler. 

I also don't understand why exactly peers (in general) need to set up their own directory, shouldn't they inhibit the directory from the "central" node? One could think about creating a temp dir upon first connection.  

Thank you so much in advance for answering.

**Comment by MangoIV** [comment]
I would also like to add that the naming of your flake outputs is not ideal. normally neovim plugins are called like `nvim-<pluginname>` in `nixpkgs` and since most people want to use it together with `nixpkgs`, you should probably adhere to that naming convention as well, if you want to make usage as easy as possible. 

This is especially important in the `overlay`, which if applies adds a new package `neovim-plugin` to the package set, which should actually be called `ethersync-nvim` and sit in `vimPlugins`, so something like 
```nix 
(self: super: 
  vimPlugins = super.vimPlugins // {
    inherit ethersync-nvim;
  };
)
```
for the plugin.

**Comment by zormit** [comment]
@MangoIV you're right, the installations instructions are out of date, we've recently changed the command-line parameters and haven't gotten around fixing the README yet.

As a workaround you could check out an older version, e.g. https://github.com/ethersync/ethersync/releases/tag/v0.2.2 (a tag that we just today introduced).

Thanks for the hints/thoughts regarding nvim and nix, I'll have a look into this.

**Comment by blinry** [comment]
Thanks for trying out Ethersync :)

I tried to bring the documentation up to date in d76ee7c1776bf99230667546696dcc5036372634. Please try again, and see if this is better!

> Additionally I'm quite confused about the nvim plugin. I wanted to try this out with somebody else and they reported it didn't work for them and it didn't work for me either

We currently require a relatively new Neovim version: 0.10! Might that be the reason for your problems? If you're on that version, can you check whether you have the `:EthersyncInfo` command? How did you install the plugin? The plugin doesn't have a lot of options right now, so we don't have a `setup()` function, it should just be active by default.

**Comment by blinry** [comment]
For the names of the flake outputs, I've renamed "neovim-plugin" to "vimPlugins.nvim-ethersync", and "neovim" to "neovim-with-ethersync" in #136, does that seem reasonable?

Feel free to suggest further improvements, your feedback is super appreciated!

**Comment by MangoIV** [comment]
> We currently require a relatively new Neovim version: 0.10! Might that be the reason for your problems? If you're on that version, can you check whether you have the :EthersyncInfo command? How did you install the plugin? The plugin doesn't have a lot of options right now, so we don't have a setup() function, it should just be active by default.

I tried again and things seem to work now with the plugin, seems like I messed up something in the hectic of trying things out. 

I think this concludes my questions and issues, thank you so much for the swift feedback!
