### ISSUE TITLE
TCP communication between peers is not transport encrypted 🔐

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#14]
I think this is worthy first issue, to also demonstrate to external users the state of our project: Quite alpha / prototype-y 👷🏼🏗️🛠️🚧 

Nevertheless, as we have already started testing the daemon as a cloud peer, I think it could make a lot of sense sense to allow to elevate the TCP Stream to a TLS stream.

**Comment by blinry** [comment]
Addressed in #66.
