### ISSUE TITLE
Daemon sometimes crashes when peers disconnect

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#145]
The error message is:

```
thread 'tokio-runtime-worker' panicked at src/peer.rs:325:18:
Failed to send on syncer_sender channel: SendError { .. }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is probably a concurrency problem – we might not want to panic on these SendErrors.

**Comment by zormit** [comment]
I think it's a case of "peer has not properly said bye and is offline/unreachable" or something in that direction.
