### ISSUE TITLE
ci: Always trigger workflows for all PRs

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#154]
The need to do this manually is probably to guard against people "using up" our CI time, right?

But right now, I'd prefer if the CI would just run automatically when a PR is updated. Haven't looked into how to make that happen.

**Comment by zormit** [comment]
https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks

It can be configured [here](https://github.com/ethersync/ethersync/settings/actions). I have changed it to the most permissive one, before it was the middle one.

<img width="802" alt="image" src="https://github.com/user-attachments/assets/d7e84c83-0e64-4fca-b1af-4f968b11b9f9">

Let's see if that helps.
