### ISSUE TITLE
"Failed to convert patch to delta" disconnects peer

### ISSUE THREAD

**Issue by gilfuser** [ethersync/ethersync#166]
Hello there. Thank you for this great project.

I'm experimenting it with neovim, in a Linux Ubuntu Studio 24.04.

I'm following the instructions in [the documentation](https://ethersync.github.io).

When I try to connect a peer in another computer in the same network, it connects and disconnects in an instant.

In the laptop that started `ethersync daemon`:

```
05:45:02  INFO ThreadId(03) ethersync::peer: Peer connected: 12D3KooWHcggVHvnTNF8kd1KdvB3crkqSZAcCzQG9w9v75SaHJrz
05:45:03  INFO ThreadId(05) ethersync::peer: Peer disconnected
```

In the laptop trying to connect with the existing session:

```
05:35:09  INFO ThreadId(03) ethersync::peer: Connected to peer 12D3KooWN8FcuE28gBwpJPt2o3JwrsmwztfkW22CR3bTaqdmyeRc
thread 'tokio-runtime-worker' panicked at src/types.rs:118:21:
Failed to convert patch to delta: "Unsupported patch action for empty path: Conflict { prop: Map(\"files\") }"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Using RUST_BACKTRACE=FULL I got this:

```
stack backtrace:
   0:     0x577ef52cca1b - <unknown>
   1:     0x577ef53089f0 - <unknown>
   2:     0x577ef52c06bd - <unknown>
   3:     0x577ef52cc804 - <unknown>
   4:     0x577ef52eecda - <unknown>
   5:     0x577ef52ee97d - <unknown>
   6:     0x577ef4de15be - <unknown>
   7:     0x577ef52ef26a - <unknown>
   8:     0x577ef52ccdfe - <unknown>
   9:     0x577ef52ccc36 - <unknown>
  10:     0x577ef52eee22 - <unknown>
  11:     0x577ef4dcd955 - <unknown>
  12:     0x577ef4e01422 - <unknown>
  13:     0x577ef4e34ed8 - <unknown>
  14:     0x577ef4e2582c - <unknown>
  15:     0x577ef4e1953e - <unknown>
  16:     0x577ef525d25b - <unknown>
  17:     0x577ef525c3d0 - <unknown>
  18:     0x577ef52402b7 - <unknown>
  19:     0x577ef525096f - <unknown>
  20:     0x577ef525b8fa - <unknown>
  21:     0x577ef523a733 - <unknown>
  22:     0x577ef52460f7 - <unknown>
  23:     0x577ef5237faa - <unknown>
  24:     0x577ef5249bc7 - <unknown>
  25:     0x577ef5247949 - <unknown>
  26:     0x577ef52c2f05 - <unknown>
  27:     0x74d306c9ca94 - start_thread
                               at ./nptl/pthread_create.c:447:8
  28:     0x74d306d29c3c - __GI___clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
  29:                0x0 - <unknown>
```

Am I doing something wrong, or there's a problem here?

Thank you

**Comment by blinry** [comment]
Hey! :) Thanks for trying the project, and for reporting this issue!

You ran into a case of #69! I'll describe the issue in more detail there, and what solutions could look like.

To solve your problem, on the machine where you use `--peer`, you can delete the file `.ethersync/doc` (which stores the CRDT state), and try to connect again (using `--peer`). As soon as you've synced once, the documents will be in a reasonable state, and you can launch the daemons independently!

Let us know if this helps – and feel welcome to subscribe to #69, to track our progress towards a solution!

**Comment by gilfuser** [comment]
Hi. Thank you for the prompt response.

Where can I find .ethersync/doc? I have a ethersync/docs in the home folder, but it's not this one, right?

**Comment by gilfuser** [comment]
Hi. It worked! Thank you!
It was a little bit fiddly because of the firewall. I turned it off and everything went just fine.
