### ISSUE TITLE
Client implementation (editor plugin) fails for Java

### ISSUE THREAD

**Issue by elbosso** [ethersync/ethersync#171]
I do suspect that this is more an issue with java than with ethersync but i will mention it here anyway. I tried to implement the protocol but ran into an interesting issue: I wanted to send a message and then read the result. If i deliberately provoked an error - all went well. But when i sent a message resulting in a success, the read on the domain socket never came back and i had to terminate the process manually.

This could have something to do with the relatively recent addition of working with domain sockets in java or with the fact that java (seemingly) only supports "streaming domain sockets" (?).

However - for future reference, i add my code here...

```java
/*
 * Copyright (c) 2024.
 *
 * Juergen Key. Alle Rechte vorbehalten.
 *
 * Weiterverbreitung und Verwendung in nichtkompilierter oder kompilierter Form,
 * mit oder ohne Veraenderung, sind unter den folgenden Bedingungen zulaessig:
 *
 *    1. Weiterverbreitete nichtkompilierte Exemplare muessen das obige Copyright,
 * die Liste der Bedingungen und den folgenden Haftungsausschluss im Quelltext
 * enthalten.
 *    2. Weiterverbreitete kompilierte Exemplare muessen das obige Copyright,
 * die Liste der Bedingungen und den folgenden Haftungsausschluss in der
 * Dokumentation und/oder anderen Materialien, die mit dem Exemplar verbreitet
 * werden, enthalten.
 *    3. Weder der Name des Autors noch die Namen der Beitragsleistenden
 * duerfen zum Kennzeichnen oder Bewerben von Produkten, die von dieser Software
 * abgeleitet wurden, ohne spezielle vorherige schriftliche Genehmigung verwendet
 * werden.
 *
 * DIESE SOFTWARE WIRD VOM AUTOR UND DEN BEITRAGSLEISTENDEN OHNE
 * JEGLICHE SPEZIELLE ODER IMPLIZIERTE GARANTIEN ZUR VERFUEGUNG GESTELLT, DIE
 * UNTER ANDEREM EINSCHLIESSEN: DIE IMPLIZIERTE GARANTIE DER VERWENDBARKEIT DER
 * SOFTWARE FUER EINEN BESTIMMTEN ZWECK. AUF KEINEN FALL IST DER AUTOR
 * ODER DIE BEITRAGSLEISTENDEN FUER IRGENDWELCHE DIREKTEN, INDIREKTEN,
 * ZUFAELLIGEN, SPEZIELLEN, BEISPIELHAFTEN ODER FOLGENDEN SCHAEDEN (UNTER ANDEREM
 * VERSCHAFFEN VON ERSATZGUETERN ODER -DIENSTLEISTUNGEN; EINSCHRAENKUNG DER
 * NUTZUNGSFAEHIGKEIT; VERLUST VON NUTZUNGSFAEHIGKEIT; DATEN; PROFIT ODER
 * GESCHAEFTSUNTERBRECHUNG), WIE AUCH IMMER VERURSACHT UND UNTER WELCHER
 * VERPFLICHTUNG AUCH IMMER, OB IN VERTRAG, STRIKTER VERPFLICHTUNG ODER
 * UNERLAUBTE HANDLUNG (INKLUSIVE FAHRLAESSIGKEIT) VERANTWORTLICH, AUF WELCHEM
 * WEG SIE AUCH IMMER DURCH DIE BENUTZUNG DIESER SOFTWARE ENTSTANDEN SIND, SOGAR,
 * WENN SIE AUF DIE MOEGLICHKEIT EINES SOLCHEN SCHADENS HINGEWIESEN WORDEN SIND.
 *
 */

package de.elbosso.util.scratch;

import org.json.JSONException;

import java.io.IOException;
import java.nio.channels.SocketChannel;

public class EtherSync
{
    public static void main(java.lang.String[]args) throws JSONException, IOException
    {
        java.io.File socketFile=new java.io.File("/tmp/ethersync");
        java.nio.file.Path socketFilePath=java.nio.file.Paths.get(socketFile.toURI());
        java.net.UnixDomainSocketAddress unixDomainSocketAddress=java.net.UnixDomainSocketAddress.of(socketFilePath);
        java.nio.channels.SocketChannel channel = java.nio.channels.SocketChannel.open(java.net.StandardProtocolFamily.UNIX);
        channel.connect(unixDomainSocketAddress);
        org.json.JSONObject open=createOpenMessage("/home/elbosso/src/language_rust/ethersync/playground/file");
        java.lang.String message=open.toString();
        System.out.println(message);
        sendMessage(message,channel);
        System.out.println(readMessage(channel));
        channel.close();
    }

    private static void sendMessage(String message, SocketChannel channel) throws IOException
    {
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(1024);
        buffer.clear();
        buffer.put(message.getBytes());
        buffer.flip();
        while (buffer.hasRemaining()) {
            channel.write(buffer);
        }
    }
    private static java.lang.String readMessage(SocketChannel channel) throws IOException {
        System.out.println(1);
        java.lang.String rv=null;
        System.out.println(2);
        java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(1024);
        System.out.println(3);
        int bytesRead = channel.read(buffer);
        System.out.println(bytesRead);
        if (bytesRead >-1)
        {
            byte[] bytes = new byte[bytesRead];
            buffer.flip();
            buffer.get(bytes);
            rv = new String(bytes);
        }
        return rv;
    }
    public static org.json.JSONObject createOpenMessage(java.lang.String filename) throws JSONException
    {
        org.json.JSONObject rv=new org.json.JSONObject();
        rv.put("jsonrpc","2.0");
        rv.put("id",uuidAsBigInteger(java.util.UUID.randomUUID()));
        rv.put("method","open");
        org.json.JSONObject parameters=new org.json.JSONObject();
        parameters.put("uri",new java.io.File(filename).toURI().toString());
        rv.put("params",parameters);
        return rv;
    }
    public static java.math.BigInteger uuidAsBigInteger(java.util.UUID id)
    {
        long hi = id.getMostSignificantBits();
        long lo = id.getLeastSignificantBits();
        byte[] bytes = java.nio.ByteBuffer.allocate(16).putLong(hi).putLong(lo).array();
        java.math.BigInteger big = new java.math.BigInteger(bytes);
        return big;
    }
}
```

**Comment by blinry** [comment]
Hello! :) Thanks for giving the implementation a try!

Make sure to talk to the daemon by spawning `ethersync client`, and talking to its stdin/stdout, as described here: https://ethersync.github.io/ethersync/editor-plugin-dev-guide.html#how-to-connect-to-the-daemon (That's the "officially supported" way, at least!)

On the socket, we expect [newline-delimited JSON](https://jsonlines.org), so maybe sending a trailing newline will help in your case?

When talking to `ethersync client`, we expect the same format that LSP clients use – JSON with a Content-Length header. The dummy-jsonrpc.py script can help you generate example messages, as described here: https://ethersync.github.io/ethersync/editor-plugin-dev-guide.html#sending-an-example-message-to-the-daemon

Let us know if this helps!

**Comment by elbosso** [comment]
Hi. Ok - I went back and tried some more. Your suggestion of adding a newline did not work out so I dug deeper: It turns out when I send a message from Java, the debug output is as follows:

```
03:58:45  INFO ThreadId(06) ethersync::editor: Client #21 connected
03:58:45 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: editor connected
03:58:45 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: open/close/edit/... message from editor #21
```

when i use the client like this: `python3 tools/dummy-jsonrpc.py daemon/playground/file | daemon/target/release/ethersync client`, the debug client is this: 

```
04:00:49  INFO ThreadId(06) ethersync::editor: Client #22 connected
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: editor connected
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: open/close/edit/... message from editor #22
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Got an 'open' message for file
04:00:49  INFO ThreadId(06) ethersync::editor: Client #22 disconnected
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: editor #22 disconnected
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Deleting cursor fd832f6770544cc889d51f5ef488d726-22
04:00:49 DEBUG ThreadId(06) ethersync::document: Stored user state for 'fd832f6770544cc889d51f5ef488d726-22': {"cursor_id":"fd832f6770544cc889d51f5ef488d726-22","name":"elbosso","file_path":"file","ranges":[]}
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: persist
04:00:49 DEBUG ThreadId(06) ethersync::daemon: Persisting!
``` 

and i get the expected response of 
```
Content-Length: 43

{"id":1,"jsonrpc":"2.0","result":"success"}
```

But when i break the command into two by first issuing `python3 tools/dummy-jsonrpc.py daemon/playground/file >te.jsonl` followed by `cat te.jsonl| daemon/target/release/ethersync client` - the debug output does appear to be the same (I see no difference)

```
04:03:19  INFO ThreadId(06) ethersync::editor: Client #23 connected
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: editor connected
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: open/close/edit/... message from editor #23
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Got an 'open' message for file
04:03:19  INFO ThreadId(06) ethersync::editor: Client #23 disconnected
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: editor #23 disconnected
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Deleting cursor fd832f6770544cc889d51f5ef488d726-23
04:03:19 DEBUG ThreadId(06) ethersync::document: Stored user state for 'fd832f6770544cc889d51f5ef488d726-23': {"cursor_id":"fd832f6770544cc889d51f5ef488d726-23","name":"elbosso","file_path":"file","ranges":[]}
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Handling doc message: persist
04:03:19 DEBUG ThreadId(06) ethersync::daemon: Persisting!
```
but there is *no* answer.

So from my point of view there are at least two cases where your implementation does seem to think that an error appears but gives no feedback - and i am especially lost about the mechanism in the secondcase...

**Comment by zormit** [comment]
Thanks for these steps to reproduce, very helpful & convenient. Even though these are our own tools, this helps to follow your train of thought.

It's surprising that you see the same debug output. I do, in the last case (`cat`), get a log that hints towards why no response is displayed:
```
INFO ThreadId(10) ethersync::daemon: Sending to editor #1 failed. It probably has disconnected, removing it from the list of known editor clients.
```
which means that the `ethersync client` was terminated too early. Maybe `python` and `cat` do something subtly different, or the "teardown" of python just leaves enough time do receive the output? As for why you did not see that INFO, I'm not sure. Maybe there's a small timeframe in which this response gets lost in the void, but Rust doesn't detect it?

Anyways, what seems to help is to actively keep the pipe open, like this: `(cat te.jsonl && cat) | daemon/target/release/ethersync client` and then close it with Ctrl+D or so.

**Comment by zormit** [comment]
One idea why the Java version _might_ fail: Our implementation is a bit picky on the whitespace. It currently expects `\r\n`, but not `/n`. I think this is something we should fix, the JSON Lines spec seems to allow both styles (either `\n` or `\r\n`).

**Comment by elbosso** [comment]
Thank you for feedback and support - the line ending issue was the solution - i forgot to mention that i did all this under Linux therefore the line ending really was `\n` only. however, I learned some more facts: the ID i generated from a randomly created UUID - the range on the server seems not to accomodate a 128 digit number. Furthermore: `java.io.File` creates URIs not accepted by the server - one must use `java.nio.file.Path` - it creates slightly different `file:` URIs. 
I just pushed the first working example java application to https://github.com/elbosso/ethersyncj !

**Comment by zormit** [comment]
Cool, thanks for writing Java Bindings! This might become helpful when someone is writing e.g. an Eclipse plugin :)

> the range on the server seems not to accomodate a 128 digit number [as jsonrpc id]

That's interesting. Technically we should accommodate for [all kinds of numbers (and even strings)](https://www.jsonrpc.org/specification#request_object):
> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. [...] The value SHOULD normally not be Null and Numbers SHOULD NOT contain fractional parts.

Currently we indeed expect something that can be parsed as `usize` in Rust. I think it's an acceptable restriction for now so I won't open a new issue, but it's good to know that we're not fully spec compliant here.
