### ISSUE TITLE
nvim 0.9.5 freeze with ethersync

### ISSUE THREAD

**Issue by sulivanShu** [ethersync/ethersync#198]
nvim 0.9.5 freeze with ethersync.

:version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742

Procedure:

1. install enthersync with Lazyvim (now all is OK)
2. restart neovim
3. run `:h` or `ZZ` command
4. neovim is freezing and need to be killed.

Other commands freeze neovim.

Fix: remove ethersync and clean lazyvim.

perhaps: "4817f6c Merge pull request #182 from ethersync/support-older-neovim" ?

**Comment by blinry** [comment]
Thanks for the bug report! :) Yeah, I think I didn't think that commit through. I could reproduce the freezes you described.

Could you try the plugin in #210, and see if it solves your issue?

**Comment by sulivanShu** [comment]
I don't think so: I'm not a developer.

I have only just figured out how to use Lazyvim.

**Comment by sulivanShu** [comment]
Sorry... And thank you for your software...

**Comment by blinry** [comment]
No worries! Let's try merging the fix – you should now be able to update the plugin by running `:Lazy`, and then pressing (uppercase) `U`.

Please let us know if that helps!

**Comment by sulivanShu** [comment]
It works! I will continue to test the plugin, and return to you if I find another bug!
