### ISSUE TITLE
SublimeText plugin

### ISSUE THREAD

**Issue by eibach** [ethersync/ethersync#230]
Is there already anybody working on a SublimeText plugin?

**Comment by blinry** [comment]
Hey :) No, not that I'm aware of! If you feel like giving it a try, the best place to start is [this page in our documentation](https://ethersync.github.io/ethersync/editor-plugin-dev-guide.html)!

**Comment by eibach** [comment]
Thanks.
Goes straight to my list of projects for those long dark evenings.
