### ISSUE TITLE
Simplify using multiple daemons: We do not want to specify the socket

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#233]
Currently it's necessary to specify the socket when you start a second daemon (on a different project). That is error prone and slightly annoying. We would prefer a simpler, more automated way.

Possible solution: Store the socket in the project `.ethersync`. Then both the daemon and the forwarder (as started by the plugin) can infer it depending on the path (where the buffer is / where the daemon is started).

**Comment by blinry** [comment]
The plugin scans for `.ethersync/` anyway, and could start the forwarder with a parameter to the parent directory of that one.

**Comment by blinry** [comment]
We're using a "quick fix" ourselves for now, where we use direnv:

`echo "export ETHERSYNC_SOCKET=/tmp/etherwiki" >> .envrc`

This will make the daemon and the client processes use the correct socket.
