### ISSUE TITLE
Re-use LSP datastructures for ranges

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#27]
To make the editor plugin code easier, we could re-use LSP's [Range](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#range) datatype. This would avoid having to rename the "head" and "anchor" entries.

Maybe not for "cursor" messages, to keep the "active end" semantic?

**Comment by zormit** [comment]
> Maybe not for "cursor" messages, to keep the "active end" semantic?

Maybe I'm misunderstanding something, but I think `start` and `end` can also be "semantically representing the active end".

A forward range would be:
```json
{
"start":{"line":0,"character":0},
"end": {"line":0,"character":10}
}
```

whereas a backward range is
```json
{
"start":{"line":0,"character":10},
"end": {"line":0,"character":0}
}
```

and then it's up to the editor how to display it.
