### ISSUE TITLE
Allow jumping to other peoples' cursors in Neovim

### ISSUE THREAD

**Issue by blinry** [ethersync/ethersync#38]
This could be a command like `<Leader>ej`, which jumps to the other user's cursor – or presents a menu if there are multiple users with cursors.

**Comment by blinry** [comment]
Partially implemented by #c52b333.

Remaining feature: When there are multiple remote cursors, show user a list, and let them pick which one to jump to.

**Comment by zormit** [comment]
I have put some thoughts today into how to finish this feature.

For the partial solution we are currently using LSP jumps. I was wondering if it maybe makes sense to utilize [marks](https://vim.fandom.com/wiki/Using_marks) more (maybe [this](https://www.reddit.com/r/vim/comments/6gqs3q/setting_marks_automatically/) is a helpful post to start thinking about it). I'm not sure though whether it's a bit "outdated" to use them? An apparently "more modern" way seems to be to use [Harpoon](https://www.reddit.com/r/neovim/comments/16dyvj4/comment/jzsr2ia/).

A "handmade" solution would probably involve rendering our own window for selecting a jump location, similarly to commandline completion ([example](https://github.com/hrsh7th/nvim-cmp)).

If we decided to use marks, we don't even need to define our own keystrokes. We could still try to support users find the right mark similarly to [this marks plugin](https://github.com/chentoast/marks.nvim).

**Comment by blinry** [comment]
My feeling is that automatically setting marks seems a bit rude. :D But we could have that as an option! Usage-wise, being able to jump to you using `'m` (jump to Moritz!) seems pretty cool!

Another solution that I could see is making use of the "count" part before our mapping, so that you could do `<count><Leader><your mapping>`, to pick who to jump to? Like, `2,j` would jump to the "second person" (however we can define an order in a more or less stable way). Not sure if it's possible to get access to that count in a custom command.
