### ISSUE TITLE
neovim complains about "file has been changed on disk" for newly created one

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#92]
bug probably introduced in #85

**Comment by zormit** [comment]
difficult because we can not test a non-existent file for whether it should be ignored.

https://github.com/BurntSushi/ripgrep/discussions/2862

**Comment by blinry** [comment]
For a quick solution, maybe fork the ignore crate.

**Comment by zormit** [comment]
Seem related to autoread issue and could be a non-issue, when we turn it off #176

**Comment by blinry** [comment]
'autoread' doesn't help for this problem at all – it doesn't prevent the check and warning W13.

We think a solution could be to immediately have Vim write the file before sending the "open", if it didn't exist.
