### ISSUE TITLE
Document safety concept with attack vectors

### ISSUE THREAD

**Issue by zormit** [ethersync/ethersync#99]
- [ ] write the documentation
- [ ] cross-check with ROS!

**Comment by blinry** [comment]
Duplicate of #117, right?

**Comment by zormit** [comment]
@blinry well, almost, but it's fine for now. I think the idea of "concept of attack vectors" is / can be viewed much broader than just the ADR on libp2p. While it's not the same angle we have included most of the ideas in the ADR, I gues.
